package com.xiaohu.springboot_mybatisgenerator.entity;

public class Mpuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mpuser.worknumber
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    private Integer worknumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mpuser.name
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mpuser.phone
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mpuser.idcard
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mpuser.birthday
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    private String birthday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mpuser.worknumber
     *
     * @return the value of mpuser.worknumber
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    public Integer getWorknumber() {
        return worknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mpuser.worknumber
     *
     * @param worknumber the value for mpuser.worknumber
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    public void setWorknumber(Integer worknumber) {
        this.worknumber = worknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mpuser.name
     *
     * @return the value of mpuser.name
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mpuser.name
     *
     * @param name the value for mpuser.name
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mpuser.phone
     *
     * @return the value of mpuser.phone
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mpuser.phone
     *
     * @param phone the value for mpuser.phone
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mpuser.idcard
     *
     * @return the value of mpuser.idcard
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mpuser.idcard
     *
     * @param idcard the value for mpuser.idcard
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mpuser.birthday
     *
     * @return the value of mpuser.birthday
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mpuser.birthday
     *
     * @param birthday the value for mpuser.birthday
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }
}