package com.xiaohu.springboot_mybatisgenerator.dao;

import com.xiaohu.springboot_mybatisgenerator.entity.Mpuser;
import com.xiaohu.springboot_mybatisgenerator.entity.MpuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MpuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mpuser
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    long countByExample(MpuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mpuser
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    int deleteByExample(MpuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mpuser
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    int deleteByPrimaryKey(Integer worknumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mpuser
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    int insert(Mpuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mpuser
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    int insertSelective(Mpuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mpuser
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    List<Mpuser> selectByExample(MpuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mpuser
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    Mpuser selectByPrimaryKey(Integer worknumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mpuser
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    int updateByExampleSelective(@Param("record") Mpuser record, @Param("example") MpuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mpuser
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    int updateByExample(@Param("record") Mpuser record, @Param("example") MpuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mpuser
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    int updateByPrimaryKeySelective(Mpuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mpuser
     *
     * @mbg.generated Fri Feb 17 14:55:50 CST 2023
     */
    int updateByPrimaryKey(Mpuser record);
}